<?php

/**
 * @file
 * Contains reddrock_custom.module..
 */

function reddrock_custom_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'reddrock_custom/reddrockcustom';
}

function reddrock_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
    
  /**
   * Apply the form_alter to a specific form #id
   * the form #id can be found through inspecting the markup
   */
  if($form['#id'] == 'views-exposed-form-listen-page-block-1') { 

	/**
	 * Extract the options from the Views Exposed Filter <select>-list 
	 */
  $links = $form['tid']['#options']; 
  

  /**
   * Iterate over the options ($links) to build an array ($pop_array) of links
   */
  $i = 0; // Initiate counter/index
  $pop_array1 = array();
  $pop_array2 = array();
	foreach ($links as $tid => $term_name) {
		if ($tid == 'All') {
			$pop_array1[$i]['#markup'] = '<span class="filter-tab"><a href="" class="active" id="' .$tid . '">' . 'See All</a></span>';
		}
		else {
			// enable toggle of tabs based on taxonomy term field value
			$term = taxonomy_term_load($tid);
			$weight = $term->get('weight')->value;
			$parental = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadParents($tid);
			$parent_term = reset($parental);
			
			if ($parent_term->id() == 11) {
				$pop_array1[$i]['#markup'] = '<span class="filter-tab"><a href="" id="' .$tid . '">' . $term_name . '</a></span>';
			}
		
			else if ($parent_term->id() == 12) {
				$pop_array2[$i]['#markup'] = '<span class="filter-tab"><a href="" id="' .$tid . '">' . $term_name . '</a></span>';
			}

			
	  	    
		}
		$i++; // Increase counter/index
	} 
	/**
	 * Create the item-list the form should render
	 */
		array_unshift($pop_array1, '<div class="track-buttons">');
		array_push($pop_array1, '</div>');
		array_unshift($pop_array2, '<div class="sfx-buttons">');
		array_push($pop_array3, '</div>');
		$form['links'] = [
			'#theme' => 'item_list',
		  '#items' => $pop_array1 . $pop_array2,
		  '#attributes' => array('class' => array('pop-list')),
		]; 
	}
  
  else {
  	//nothing...
  } 
}