<?php

/**
 * @file
 * Contains reddrock_custom.module..
 */

function reddrock_custom_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'reddrock_custom/reddrockcustom';
}

function reddrock_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
    
  /**
   * Apply the form_alter to a specific form #id
   * the form #id can be found through inspecting the markup
   */
  if($form['#id'] == 'views-exposed-form-listen-page-block-1') { 

	/**
	 * Extract the options from the Views Exposed Filter <select>-list 
	 */
  $links = $form['tid']['#options']; 
  

  /**
   * Iterate over the options ($links) to build an array ($pop_array) of links
   */
  $i = 0; // Initiate counter/index
  $pop_array1 = array();
  $pop_array2 = array();
	foreach ($links as $tid => $term_name) {
		if ($tid == 'All') {
			$pop_array1[$i]['#markup'] = '<span class="filter-tab"><a href="" class="active" id="' .$tid . '">' . 'See All</a></span>';
		}
		else {
			// enable toggle of tabs based on taxonomy term field value
			$term = taxonomy_term_load($tid);
			$weight = $term->get('weight')->value;
			print_r($term);
		//	$list = [];
		//	foreach ($parent as $parentterm) {
	//		  $list[$parentterm->id()] = $parentterm->label();
	//		}print_r($list);
			

			
	  	    
		}
		$i++; // Increase counter/index
	} 
	/**
	 * Create the item-list the form should render
	 */
		$form['links'] = [
			'#theme' => 'item_list',
		  '#items' => $pop_array1,
		  '#attributes' => array('class' => array('pop-list')),
		]; 
	}
  
  else {
  	//nothing...
  } 
}